export const FETCH_TOP_SALES_REQUEST = 'FETCH_TOP_SALES_REQUEST';
export const FETCH_TOP_SALES_SUCCESS = 'FETCH_TOP_SALES_SUCCESS';
export const FETCH_TOP_SALES_FAILURE = 'FETCH_TOP_SALES_FAILURE';

export const CHANGE_ACTIVE_CATEGORY = 'CHANGE_ACTIVE_CATEGORY';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const FETCH_MORE_ITEMS_REQUEST = 'FETCH_MORE_ITEMS_REQUEST';
export const FETCH_MORE_ITEMS_SUCCESS = 'FETCH_MORE_ITEMS_SUCCESS';
export const FETCH_MORE_ITEMS_FAILURE = 'FETCH_MORE_ITEMS_FAILURE';

export const FETCH_SEARCH_ITEMS_REQUEST = 'FETCH_SEARCH_ITEMS_REQUEST';
export const FETCH_SEARCH_ITEMS_SUCCESS = 'FETCH_SEARCH_ITEMS_SUCCESS';
export const FETCH_SEARCH_ITEMS_FAILURE = 'FETCH_SEARCH_ITEMS_FAILURE';

export const SET_SEARCH = 'SET_SEARCH';

export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';

export const CHANGE_SIZE_ITEM = 'CHANGE_SIZE_ITEM';
export const CHANGE_COUNT_ITEM = 'CHANGE_COUNT_ITEM';

export const SET_LOCAL_CART_ITEMS = 'SET_LOCAL_CART_ITEMS';
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const REMOVE_CART_IETMS = 'REMOVE_CART_IETMS';

export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';
